[Document]
index-html = "index.html"
filesystem-root = "root"

[[Document.Install]]
name = "stak"
package = "stak"

[[Document.Install]]
name = "stak-compile"
package = "stak-compile"

[Machine]
stage2 = { flavor = "node", workdir = "../../stage2-loader", build = "build.mjs" }
stage3 = { flavor = "rust", package = "wasi-document-unzip", bin = "unzip" }
