[Document]
index-html = "index.html"
filesystem-root = "root"

[[Document.Install]]
git = "https://github.com/uutils/coreutils"
package = "coreutils"
default-features = false
features = ["feat_wasm"]

[Machine]
stage2 = { flavor = "node", workdir = "../../stage2-loader", build = "build.mjs" }
stage3 = { flavor = "rust", package = "wasi-document-unzip", bin = "unzip" }
